apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: nginx:1.26-alpine
          command: ["/bin/sh"]
          args:
            - -c
            - |
              apk add --no-cache gettext
              envsubst < /usr/share/nginx/html/index.html > /tmp/index.html
              mv /tmp/index.html /usr/share/nginx/html/index.html
              nginx -g "daemon off;"
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-content
          configMap:
            name: nginx-demo-html
  # Canary strategy for progressive delivery
  strategy:
    canary:
      # Services for canary traffic splitting
      canaryService: nginx-demo-canary
      stableService: nginx-demo-stable
      # Traffic routing via ALB
      trafficRouting:
        alb:
          ingress: nginx-demo
          rootService: nginx-demo-stable
          servicePort: 80
          annotationPrefix: alb.ingress.kubernetes.io
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 75
        - pause: { duration: 30s }
        - setWeight: 100
