apiVersion: v1
kind: Secret
metadata:
  name: atlantis-demo-secrets
  labels:
    app: atlantis-demo
type: Opaque
stringData:
  # GitHub user (optional - for GitHub App authentication)
  github-user: ""
  # GitHub token (optional - set via kubectl or external secrets)
  github-token: ""
  # Webhook secret (optional - for webhook validation)
  # Generate with: openssl rand -hex 16
  webhook-secret: ""
