apiVersion: v1
kind: Secret
metadata:
  name: atlantis-demo-secrets
  labels:
    app: atlantis-demo
type: Opaque
stringData:
  # GitHub user (for testing: use "test" - for production: use real username)
  # Atlantis requires at least one auth method to start
  # For testing deployment, use dummy value "test"
  # For full functionality, set your GitHub username
  github-user: "test"
  # GitHub token (for testing: use "test" - for production: use real token)
  # Atlantis requires at least one auth method to start
  # For testing deployment, use dummy value "test" (won't work for PRs)
  # For full functionality, create token at: https://github.com/settings/tokens
  # Required scopes: repo, admin:repo_hook, write:repo_hook
  github-token: "test"
  # Webhook secret (optional - for webhook validation)
  # Generate with: openssl rand -hex 16
  webhook-secret: ""
